#!/bin/sh /etc/rc.common
# SecuBox Streamlit Platform - Python data app hosting
# Copyright (C) 2025 CyberMind.fr

START=95
STOP=10
USE_PROCD=1

PROG=/usr/sbin/streamlitctl
CONFIG=streamlit

start_service() {
	local enabled
	config_load "$CONFIG"
	config_get enabled main enabled '0'

	[ "$enabled" = "1" ] || {
		echo "Streamlit is disabled. Enable with: uci set streamlit.main.enabled=1"
		return 0
	}

	procd_open_instance
	procd_set_param command "$PROG" service-run
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	"$PROG" service-stop
}

service_triggers() {
	procd_add_reload_trigger "$CONFIG"
}

reload_service() {
	stop
	start
}

status() {
	"$PROG" status
}
