#!/bin/sh /etc/rc.common
# Network Anomaly Detection Daemon

START=95
STOP=10
USE_PROCD=1

PROG="/usr/bin/network-anomalyctl"
CONFIG="network-anomaly"

start_service() {
	local enabled

	config_load "$CONFIG"
	config_get enabled main enabled 0

	[ "$enabled" = "1" ] || return 0

	procd_open_instance
	procd_set_param command "$PROG" daemon
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "$CONFIG"
}

reload_service() {
	stop
	start
}
