#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1
SERVICE_NAME="mqtt-bridge-monitor"

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/mqtt-bridge-monitor
	procd_set_param respawn 0 5 5
	procd_close_instance
}
