# LXC configuration for APPNAME
# Auto-generated by RezApp Forge from SOURCE_IMAGE

lxc.uts.name = APPNAME
lxc.rootfs.path = dir:/srv/lxc/APPNAME/rootfs
lxc.init.cmd = /start-lxc.sh

# Share host network namespace
lxc.namespace.share.net = 1

# Drop dangerous capabilities
lxc.cap.drop = sys_admin sys_boot sys_module sys_rawio sys_time

# Memory limit
lxc.cgroup2.memory.max = MEMORY

# TTY configuration
lxc.tty.max = 1
lxc.pty.max = 1

# Mount configuration
lxc.mount.auto = proc:mixed sys:ro cgroup:mixed

# Environment
lxc.environment = PUID=UID
lxc.environment = PGID=GID
lxc.environment = TZ=UTC
