#!/bin/bash
# LXC startup wrapper for APPNAME
# Auto-generated by RezApp Forge from SOURCE_IMAGE

# Set UID/GID if specified
export PUID=${PUID:-UID}
export PGID=${PGID:-GID}

# Create required directories
mkdir -p /config /data /tmp

# Change to non-root user if specified
if [ "$PUID" != "0" ] && [ "$PGID" != "0" ]; then
	# Create user if not exists
	if ! id -u app >/dev/null 2>&1; then
		addgroup -g $PGID app 2>/dev/null || true
		adduser -D -u $PUID -G app app 2>/dev/null || true
	fi
fi

# Execute the original entrypoint
# ENTRYPOINT_PLACEHOLDER
exec /bin/sh
