#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

start_service() {
    [ "$(uci -q get webtorrent.main.enabled)" = "1" ] || return 0
    webtorrentctl start
}

stop_service() {
    webtorrentctl stop
}

restart() {
    webtorrentctl restart
}

status() {
    webtorrentctl status
}
