#!/bin/sh /etc/rc.common
# SecuBox Nextcloud LXC Service
# Copyright (C) 2025 CyberMind.fr

START=90
STOP=10
USE_PROCD=1

PROG=/usr/sbin/nextcloudctl
CONFIG=nextcloud

start_service() {
	local enabled

	config_load "$CONFIG"
	config_get enabled main enabled '0'

	[ "$enabled" = "1" ] || return 0

	procd_open_instance
	procd_set_param command "$PROG" service-run
	procd_set_param respawn 3600 5 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param pidfile /var/run/nextcloud.pid
	procd_close_instance
}

stop_service() {
	"$PROG" service-stop
}

reload_service() {
	stop_service
	start_service
}

service_triggers() {
	procd_add_reload_trigger "$CONFIG"
}
