#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

PROG="/usr/sbin/mac-guardian"

start_service() {
	local enabled
	config_load mac-guardian
	config_get enabled main enabled 0
	[ "$enabled" = "1" ] || return 0

	procd_open_instance
	procd_set_param command "$PROG" start
	procd_set_param pidfile /var/run/mac-guardian.pid
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "mac-guardian" "wireless"
}
