<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Development Status - {{HOSTNAME}}</title>
<style>
:root{--bg:#0a0a0f;--surface:#12121a;--card:#1a1a2e;--ink:#f0f2ff;--dim:rgba(240,242,255,.5);--muted:#666;--primary:#6366f1;--primary-end:#8b5cf6;--cyan:#06b6d4;--green:#22c55e;--red:#ef4444;--yellow:#f59e0b;--glass:rgba(255,255,255,.04);--border:rgba(255,255,255,.08)}
*{margin:0;padding:0;box-sizing:border-box}
body{min-height:100vh;background:var(--bg);color:var(--ink);font-family:"Inter","Segoe UI",system-ui,sans-serif;padding:2rem;line-height:1.6}
.container{max-width:1200px;margin:0 auto}
h1{font-size:2rem;margin-bottom:.5rem;background:linear-gradient(90deg,var(--primary),var(--primary-end),var(--cyan));-webkit-background-clip:text;-webkit-text-fill-color:transparent}
.header{display:flex;justify-content:space-between;align-items:flex-start;flex-wrap:wrap;gap:1rem;margin-bottom:2rem;padding:1.5rem;background:var(--card);border:1px solid var(--border);border-radius:12px}
.header-meta{display:flex;gap:1rem;flex-wrap:wrap}
.meta-item{font-size:.75rem;color:var(--muted);padding:.25rem .75rem;background:var(--glass);border-radius:4px}
.score-badge{font-size:2rem;font-weight:700;padding:1rem 1.5rem;background:linear-gradient(135deg,var(--primary),var(--primary-end));border-radius:12px;text-align:center}
.score-label{font-size:.6rem;text-transform:uppercase;letter-spacing:.1em;opacity:.7;display:block;margin-top:.25rem}
.card{background:var(--card);border:1px solid var(--border);border-radius:12px;padding:1.25rem;margin-bottom:1.5rem}
.card-header{display:flex;justify-content:space-between;align-items:center;margin-bottom:1rem;padding-bottom:.75rem;border-bottom:1px solid var(--border)}
.card-title{font-size:1rem;font-weight:600;display:flex;align-items:center;gap:.5rem}
.card-title::before{content:"";width:3px;height:1em;background:var(--primary);border-radius:2px}
ul{list-style:none;padding-left:0}
li{padding:.5rem 0;border-bottom:1px solid var(--border);font-size:.9rem}
li:last-child{border-bottom:none}
li strong{color:var(--cyan)}
.history-entry{margin-bottom:1.5rem}
.history-date{font-size:.8rem;color:var(--primary);font-weight:600;margin-bottom:.5rem;padding:.25rem .5rem;background:rgba(99,102,241,.1);border-radius:4px;display:inline-block}
.wip-section{margin-bottom:1rem}
.wip-section h4{color:var(--cyan);font-size:.85rem;margin-bottom:.5rem}
.roadmap-version{display:flex;align-items:center;gap:1rem;padding:.75rem;background:var(--glass);border-radius:8px;margin-bottom:.5rem}
.roadmap-version h4{margin:0;flex:1}
.status-badge{font-size:.65rem;padding:.25rem .5rem;border-radius:4px;text-transform:uppercase;font-weight:600}
.status-badge.complete{background:rgba(34,197,94,.15);color:var(--green)}
.status-badge.inprogress{background:rgba(99,102,241,.15);color:var(--primary)}
.status-badge.pending{background:rgba(102,102,102,.15);color:var(--muted)}
.muted{color:var(--muted);font-style:italic}
footer{margin-top:3rem;text-align:center;color:var(--muted);font-size:.75rem;padding-top:1.5rem;border-top:1px solid var(--border)}
footer a{color:var(--primary)}
</style>
</head>
<body>
<div class="container">
    <div class="header">
        <div class="header-info">
            <h1>Development Status Report</h1>
            <div class="header-meta">
                <span class="meta-item">{{HOSTNAME}}</span>
                <span class="meta-item">{{TIMESTAMP}}</span>
            </div>
        </div>
        <div class="score-badge">
            {{HEALTH_SCORE}}%
            <span class="score-label">Health Score</span>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Recent Completions</h3>
        </div>
        <div class="card-body">
            {{HISTORY_ENTRIES}}
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Work In Progress</h3>
        </div>
        <div class="card-body">
            {{WIP_ENTRIES}}
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Roadmap Progress</h3>
        </div>
        <div class="card-body">
            {{ROADMAP_DATA}}
        </div>
    </div>

    <footer>
        Generated by SecuBox Report Generator v1.0
    </footer>
</div>
</body>
</html>
