<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{SUBJECT}}</title>
</head>
<body style="margin:0;padding:0;background:#0a0a0f;font-family:'Segoe UI',system-ui,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#0a0a0f;padding:20px;">
<tr>
<td align="center">
<table width="600" cellpadding="0" cellspacing="0" style="background:#1a1a2e;border-radius:12px;overflow:hidden;">
<!-- Header -->
<tr>
<td style="background:linear-gradient(135deg,#6366f1,#8b5cf6);padding:30px;text-align:center;">
<h1 style="margin:0;color:#fff;font-size:24px;">SecuBox Report</h1>
<p style="margin:10px 0 0;color:rgba(255,255,255,0.8);font-size:14px;">{{HOSTNAME}} | {{TIMESTAMP}}</p>
</td>
</tr>
<!-- Content -->
<tr>
<td style="padding:30px;color:#f0f2ff;">
{{CONTENT}}
</td>
</tr>
<!-- Footer -->
<tr>
<td style="padding:20px;text-align:center;border-top:1px solid rgba(255,255,255,0.08);color:#666;font-size:12px;">
Generated by SecuBox Report Generator<br>
<a href="{{DASHBOARD_URL}}" style="color:#6366f1;text-decoration:none;">View Dashboard</a>
</td>
</tr>
</table>
</td>
</tr>
</table>
</body>
</html>
